# Generated by Django 5.1.5 on 2025-03-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_user_is_specialist_remove_user_second_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
