# Generated by Django 5.1.5 on 2025-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0006_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_choices',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='', max_length=20),
        ),
    ]
