# Generated by Django 5.1.5 on 2025-03-29 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0007_booking_service_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_dt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_choices',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='upcoming', max_length=20),
        ),
    ]
